<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.214" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Takt.Shared\Takt.Shared.csproj" />
  </ItemGroup>

</Project>
