<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Scriban" Version="7.2.4" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.214" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Takt.Domain\Takt.Domain.csproj" />
    <ProjectReference Include="..\Takt.Shared\Takt.Shared.csproj" />
  </ItemGroup>

</Project>
