// ========================================
// 项目名称：节拍工厂·Takt Plat
// 命名空间：Takt.Shared.Helpers
// 文件名称：TaktDatabaseBackupPathHelper.cs
// 创建时间：2026-07-19
// 创建人：Takt365(Cursor AI)
// 功能描述：数据库备份文件名解析与校验（默认 z{库名}_{Full|Delta}_{时间戳}.bak）
//
// 版权信息：Copyright (c) 2026 Takt  All rights reserved.
// 免责声明：此软件使用 MIT License，作者不承担任何使用风险。
// ========================================

using System.Text.RegularExpressions;

namespace Takt.Shared.Helpers;

/// <summary>
/// 数据库备份路径/文件名辅助
/// </summary>
public static class TaktDatabaseBackupPathHelper
{
    /// <summary>完整备份类型</summary>
    public const int BackupTypeFull = 1;

    /// <summary>增量备份类型</summary>
    public const int BackupTypeDelta = 2;

    private static readonly Regex SafeDbNamePart = new(@"^[A-Za-z0-9_\-\.]+$", RegexOptions.Compiled);

    private static readonly Regex SafeBackupFileName = new(@"^[A-Za-z0-9_\-\.]+\.bak$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <summary>
    /// 自动生成文件名模式：z{库名}_{Full|Delta}_{14位时间戳}.bak
    /// </summary>
    private static readonly Regex AutoGeneratedBackupFileName = new(
        @"^z[A-Za-z0-9_\-\.]+_(Full|Delta)_\d{14}\.bak$",
        RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <summary>
    /// 生成默认备份文件名：z{库名}_{Full|Delta}_{yyyyMMddHHmmss}.bak
    /// </summary>
    /// <param name="databaseName">库展示名（如 Takt_000_Dev）</param>
    /// <param name="backupType">1=Full 2=Delta</param>
    /// <param name="stamp">可选时间戳；为空则取当前本地时间</param>
    /// <returns>默认文件名</returns>
    /// <exception cref="ArgumentException">库名非法或备份类型非法</exception>
    public static string BuildDefaultBackupFileName(string databaseName, int backupType, DateTime? stamp = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(databaseName);
        var safeDb = databaseName.Trim();
        if (!SafeDbNamePart.IsMatch(safeDb))
        {
            throw new ArgumentException($"非法数据库名: {databaseName}");
        }
        var typeLabel = ResolveTypeLabel(backupType);
        var time = (stamp ?? DateTime.Now).ToString("yyyyMMddHHmmss");
        return $"z{safeDb}_{typeLabel}_{time}.bak";
    }

    /// <summary>
    /// 是否为自动生成的默认备份文件名
    /// </summary>
    /// <param name="fileName">文件名</param>
    /// <returns>是否匹配默认模式</returns>
    public static bool IsAutoGeneratedBackupFileName(string? fileName)
    {
        if (string.IsNullOrWhiteSpace(fileName))
        {
            return false;
        }
        return AutoGeneratedBackupFileName.IsMatch(Path.GetFileName(fileName.Trim()));
    }

    /// <summary>
    /// 解析并校验备份文件名（空则按类型生成默认名）
    /// </summary>
    /// <param name="fileName">用户文件名；空则自动生成</param>
    /// <param name="databaseName">库名</param>
    /// <param name="backupType">1=Full 2=Delta</param>
    /// <returns>合法文件名</returns>
    /// <exception cref="ArgumentException">非法文件名或库名</exception>
    public static string ResolveBackupFileName(string? fileName, string databaseName, int backupType = BackupTypeFull)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(databaseName);
        if (!SafeDbNamePart.IsMatch(databaseName.Trim()))
        {
            throw new ArgumentException($"非法数据库名: {databaseName}");
        }
        if (string.IsNullOrWhiteSpace(fileName))
        {
            return BuildDefaultBackupFileName(databaseName, backupType);
        }
        var name = Path.GetFileName(fileName.Trim());
        if (!name.EndsWith(".bak", StringComparison.OrdinalIgnoreCase))
        {
            name += ".bak";
        }
        if (!SafeBackupFileName.IsMatch(name))
        {
            throw new ArgumentException("备份文件名仅允许字母数字下划线短横点，且须为 .bak");
        }
        return name;
    }

    /// <summary>
    /// 解析执行时实际落盘文件名：空或默认模式则按当前时间重新生成；自定义名原样校验
    /// </summary>
    /// <param name="fileName">配置中的文件名</param>
    /// <param name="databaseName">库名</param>
    /// <param name="backupType">1=Full 2=Delta</param>
    /// <returns>本次执行文件名</returns>
    public static string ResolveBackupFileNameForRun(string? fileName, string databaseName, int backupType)
    {
        if (string.IsNullOrWhiteSpace(fileName) || IsAutoGeneratedBackupFileName(fileName))
        {
            return BuildDefaultBackupFileName(databaseName, backupType);
        }
        return ResolveBackupFileName(fileName, databaseName, backupType);
    }

    /// <summary>
    /// 备份类型 → Full / Delta
    /// </summary>
    /// <param name="backupType">1=Full 2=Delta</param>
    /// <returns>类型标签</returns>
    /// <exception cref="ArgumentException">类型非法</exception>
    private static string ResolveTypeLabel(int backupType)
    {
        return backupType switch
        {
            BackupTypeFull => "Full",
            BackupTypeDelta => "Delta",
            _ => throw new ArgumentException("备份类型须为 1(Full) 或 2(Delta)"),
        };
    }
}
