/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BOM_MATERIAL_COST_ITEM_TABLE_NAME: typeof import('./composables/use-bom-material-cost-item-recalculate-signalr').BOM_MATERIAL_COST_ITEM_TABLE_NAME
  const EC_NOTIFICATION_TABLE_NAME: typeof import('./composables/use-ec-change-signalr-refresh').EC_NOTIFICATION_TABLE_NAME
  const EffectScope: typeof import('vue').EffectScope
  const Modal: typeof import('ant-design-vue').Modal
  const QUARTZ_TABLE_NAME: typeof import('./composables/use-quartz-signalr-refresh').QUARTZ_TABLE_NAME
  const TAKT_CAPTCHA_BEHAVIOR_TRACK_HEIGHT: typeof import('./composables/use-takt-captcha-behavior').TAKT_CAPTCHA_BEHAVIOR_TRACK_HEIGHT
  const TAKT_CAPTCHA_SLIDER_TRACK_HEIGHT: typeof import('./composables/use-takt-captcha-slider').TAKT_CAPTCHA_SLIDER_TRACK_HEIGHT
  const TAKT_MASTER_DETAIL_LR_SCROLL_Y_KEY: typeof import('./composables/use-takt-master-detail-lr-scroll-y').TAKT_MASTER_DETAIL_LR_SCROLL_Y_KEY
  const WORKFLOW_TABLE_NAMES: typeof import('./composables/use-workflow-signalr-refresh').WORKFLOW_TABLE_NAMES
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createLogger: typeof import('@/utils/logger').createLogger
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const formatBomMaterialCostItemRecalculateDuration: typeof import('./composables/use-bom-material-cost-item-recalculate-signalr').formatBomMaterialCostItemRecalculateDuration
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isTaktCaptchaDisabledError: typeof import('./composables/use-takt-login-captcha').isTaktCaptchaDisabledError
  const logger: typeof import('@/utils/logger').logger
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const measureMasterDetailLrTableScrollY: typeof import('./composables/use-takt-master-detail-lr-scroll-y').measureMasterDetailLrTableScrollY
  const message: typeof import('ant-design-vue').message
  const nextTick: typeof import('vue').nextTick
  const notification: typeof import('ant-design-vue').notification
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const probeSessionCaptchaRequiredAsync: typeof import('./composables/use-takt-login-captcha').probeSessionCaptchaRequiredAsync
  const provide: typeof import('vue').provide
  const provideTaktMasterDetailLrScrollY: typeof import('./composables/use-takt-master-detail-lr-scroll-y').provideTaktMasterDetailLrScrollY
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveCurrentCompanyRelatedPlantCode: typeof import('./composables/use-company-related-plant').resolveCurrentCompanyRelatedPlantCode
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useBomMaterialCostItemRecalculateSignalR: typeof import('./composables/use-bom-material-cost-item-recalculate-signalr').useBomMaterialCostItemRecalculateSignalR
  const useBusinessScopeRouteKey: typeof import('./composables/use-business-scope-route-key').useBusinessScopeRouteKey
  const useCompanyRelatedPlant: typeof import('./composables/use-company-related-plant').useCompanyRelatedPlant
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDatabaseInfoCatalog: typeof import('./composables/use-database-info-catalog').useDatabaseInfoCatalog
  const useEcChangeSignalRRefresh: typeof import('./composables/use-ec-change-signalr-refresh').useEcChangeSignalRRefresh
  const useEcExecSignalRGroup: typeof import('./composables/use-ec-dept-signalr-group').useEcExecSignalRGroup
  const useEntityFieldI18n: typeof import('./composables/use-entity-field-i18n').useEntityFieldI18n
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useLoginFieldSync: typeof import('./composables/use-login-field-sync').useLoginFieldSync
  const useModel: typeof import('vue').useModel
  const useQuartzSignalRRefresh: typeof import('./composables/use-quartz-signalr-refresh').useQuartzSignalRRefresh
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTableRefresh: typeof import('./composables/use-table-refresh').useTableRefresh
  const useTaktCaptchaBehavior: typeof import('./composables/use-takt-captcha-behavior').useTaktCaptchaBehavior
  const useTaktCaptchaSlider: typeof import('./composables/use-takt-captcha-slider').useTaktCaptchaSlider
  const useTaktComponentLocale: typeof import('./composables/use-takt-component-locale').useTaktComponentLocale
  const useTaktFlowSubmit: typeof import('./composables/use-takt-flow-submit').useTaktFlowSubmit
  const useTaktLoginCaptcha: typeof import('./composables/use-takt-login-captcha').useTaktLoginCaptcha
  const useTaktMasterDetailLrScrollY: typeof import('./composables/use-takt-master-detail-lr-scroll-y').useTaktMasterDetailLrScrollY
  const useTaktTableBodyScrollY: typeof import('./composables/use-takt-table-body-scroll-y').useTaktTableBodyScrollY
  const useTaktTableContainerScrollY: typeof import('./composables/use-takt-table-container-scroll-y').useTaktTableContainerScrollY
  const useTaktTableViewportScrollY: typeof import('./composables/use-takt-table-viewport-scroll-y').useTaktTableViewportScrollY
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useWorkflowSignalRRefresh: typeof import('./composables/use-workflow-signalr-refresh').useWorkflowSignalRRefresh
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { EntityFieldPlaceholderKind } from './composables/use-entity-field-i18n'
  import('./composables/use-entity-field-i18n')
  // @ts-ignore
  export type { UseLoginFieldSyncOptions } from './composables/use-login-field-sync'
  import('./composables/use-login-field-sync')
  // @ts-ignore
  export type { TaktCaptchaPanelExpose, UseTaktLoginCaptchaOptions } from './composables/use-takt-login-captcha'
  import('./composables/use-takt-login-captcha')
  // @ts-ignore
  export type { TaktMasterDetailLrScrollMeasureRefs, MeasureMasterDetailLrTableScrollYOptions } from './composables/use-takt-master-detail-lr-scroll-y'
  import('./composables/use-takt-master-detail-lr-scroll-y')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly BOM_MATERIAL_COST_ITEM_TABLE_NAME: UnwrapRef<typeof import('./composables/use-bom-material-cost-item-recalculate-signalr')['BOM_MATERIAL_COST_ITEM_TABLE_NAME']>
    readonly EC_NOTIFICATION_TABLE_NAME: UnwrapRef<typeof import('./composables/use-ec-change-signalr-refresh')['EC_NOTIFICATION_TABLE_NAME']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly Modal: UnwrapRef<typeof import('ant-design-vue')['Modal']>
    readonly QUARTZ_TABLE_NAME: UnwrapRef<typeof import('./composables/use-quartz-signalr-refresh')['QUARTZ_TABLE_NAME']>
    readonly TAKT_CAPTCHA_BEHAVIOR_TRACK_HEIGHT: UnwrapRef<typeof import('./composables/use-takt-captcha-behavior')['TAKT_CAPTCHA_BEHAVIOR_TRACK_HEIGHT']>
    readonly TAKT_CAPTCHA_SLIDER_TRACK_HEIGHT: UnwrapRef<typeof import('./composables/use-takt-captcha-slider')['TAKT_CAPTCHA_SLIDER_TRACK_HEIGHT']>
    readonly TAKT_MASTER_DETAIL_LR_SCROLL_Y_KEY: UnwrapRef<typeof import('./composables/use-takt-master-detail-lr-scroll-y')['TAKT_MASTER_DETAIL_LR_SCROLL_Y_KEY']>
    readonly WORKFLOW_TABLE_NAMES: UnwrapRef<typeof import('./composables/use-workflow-signalr-refresh')['WORKFLOW_TABLE_NAMES']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createLogger: UnwrapRef<typeof import('@/utils/logger')['createLogger']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly formatBomMaterialCostItemRecalculateDuration: UnwrapRef<typeof import('./composables/use-bom-material-cost-item-recalculate-signalr')['formatBomMaterialCostItemRecalculateDuration']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly isTaktCaptchaDisabledError: UnwrapRef<typeof import('./composables/use-takt-login-captcha')['isTaktCaptchaDisabledError']>
    readonly logger: UnwrapRef<typeof import('@/utils/logger')['logger']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly measureMasterDetailLrTableScrollY: UnwrapRef<typeof import('./composables/use-takt-master-detail-lr-scroll-y')['measureMasterDetailLrTableScrollY']>
    readonly message: UnwrapRef<typeof import('ant-design-vue')['message']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly notification: UnwrapRef<typeof import('ant-design-vue')['notification']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly probeSessionCaptchaRequiredAsync: UnwrapRef<typeof import('./composables/use-takt-login-captcha')['probeSessionCaptchaRequiredAsync']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly provideTaktMasterDetailLrScrollY: UnwrapRef<typeof import('./composables/use-takt-master-detail-lr-scroll-y')['provideTaktMasterDetailLrScrollY']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveCurrentCompanyRelatedPlantCode: UnwrapRef<typeof import('./composables/use-company-related-plant')['resolveCurrentCompanyRelatedPlantCode']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBomMaterialCostItemRecalculateSignalR: UnwrapRef<typeof import('./composables/use-bom-material-cost-item-recalculate-signalr')['useBomMaterialCostItemRecalculateSignalR']>
    readonly useBusinessScopeRouteKey: UnwrapRef<typeof import('./composables/use-business-scope-route-key')['useBusinessScopeRouteKey']>
    readonly useCompanyRelatedPlant: UnwrapRef<typeof import('./composables/use-company-related-plant')['useCompanyRelatedPlant']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDatabaseInfoCatalog: UnwrapRef<typeof import('./composables/use-database-info-catalog')['useDatabaseInfoCatalog']>
    readonly useEcChangeSignalRRefresh: UnwrapRef<typeof import('./composables/use-ec-change-signalr-refresh')['useEcChangeSignalRRefresh']>
    readonly useEcExecSignalRGroup: UnwrapRef<typeof import('./composables/use-ec-dept-signalr-group')['useEcExecSignalRGroup']>
    readonly useEntityFieldI18n: UnwrapRef<typeof import('./composables/use-entity-field-i18n')['useEntityFieldI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLoginFieldSync: UnwrapRef<typeof import('./composables/use-login-field-sync')['useLoginFieldSync']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useQuartzSignalRRefresh: UnwrapRef<typeof import('./composables/use-quartz-signalr-refresh')['useQuartzSignalRRefresh']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTableRefresh: UnwrapRef<typeof import('./composables/use-table-refresh')['useTableRefresh']>
    readonly useTaktCaptchaBehavior: UnwrapRef<typeof import('./composables/use-takt-captcha-behavior')['useTaktCaptchaBehavior']>
    readonly useTaktCaptchaSlider: UnwrapRef<typeof import('./composables/use-takt-captcha-slider')['useTaktCaptchaSlider']>
    readonly useTaktComponentLocale: UnwrapRef<typeof import('./composables/use-takt-component-locale')['useTaktComponentLocale']>
    readonly useTaktFlowSubmit: UnwrapRef<typeof import('./composables/use-takt-flow-submit')['useTaktFlowSubmit']>
    readonly useTaktLoginCaptcha: UnwrapRef<typeof import('./composables/use-takt-login-captcha')['useTaktLoginCaptcha']>
    readonly useTaktMasterDetailLrScrollY: UnwrapRef<typeof import('./composables/use-takt-master-detail-lr-scroll-y')['useTaktMasterDetailLrScrollY']>
    readonly useTaktTableContainerScrollY: UnwrapRef<typeof import('./composables/use-takt-table-container-scroll-y')['useTaktTableContainerScrollY']>
    readonly useTaktTableViewportScrollY: UnwrapRef<typeof import('./composables/use-takt-table-viewport-scroll-y')['useTaktTableViewportScrollY']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useWorkflowSignalRRefresh: UnwrapRef<typeof import('./composables/use-workflow-signalr-refresh')['useWorkflowSignalRRefresh']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}