// ========================================
// 项目名称：节拍工厂·Takt Plat 
// 命名空间：Takt.Shared.Options
// 文件名称：TaktExcelOptions.cs
// 创建时间：2025-01-20
// 创建人：Takt365(Cursor AI)
// 功能描述：Excel 导入导出配置；Options 内嵌安全底线默认值，appsettings 仅为覆盖项
// 
// 版权信息：Copyright (c) 2025 Takt  All rights reserved.
// 免责声明：此软件使用 MIT License，作者不承担任何使用风险。
// ========================================

namespace Takt.Shared.Options;

/// <summary>
/// Excel 配置（<c>appsettings:Excel</c> 覆盖本类默认值；启动期 <see cref="Validate"/> 校验范围与硬上限）
/// </summary>
public class TaktExcelOptions
{
    /// <summary>
    /// appsettings 配置节名称
    /// </summary>
    public const string SectionName = "Excel";

    /// <summary>
    /// 作者
    /// </summary>
    public string Author { get; set; } = "Takt365";

    /// <summary>
    /// 标题
    /// </summary>
    public string Title { get; set; } = "Takt Plat Export";

    /// <summary>
    /// 主题
    /// </summary>
    public string Subject { get; set; } = "Takt Plat Data Export";

    /// <summary>
    /// 类别
    /// </summary>
    public string Category { get; set; } = "Export";

    /// <summary>
    /// 关键词
    /// </summary>
    public string Keywords { get; set; } = "Takt,Export,Excel";

    /// <summary>
    /// 备注
    /// </summary>
    public string Comments { get; set; } = "Generated by Takt Plat";

    /// <summary>
    /// 状态
    /// </summary>
    public string Status { get; set; } = "Final";

    /// <summary>
    /// 应用程序名称
    /// </summary>
    public string Application { get; set; } = "Takt Plat";

    /// <summary>
    /// 公司
    /// </summary>
    public string Company { get; set; } = "Takt Technologies Co., Ltd.";

    /// <summary>
    /// 管理者
    /// </summary>
    public string Manager { get; set; } = "Takt365";

    /// <summary>
    /// 导入行数与安全边界（默认值见 <see cref="TaktExcelImportOptions"/>）
    /// </summary>
    public TaktExcelImportOptions Import { get; set; } = new();

    /// <summary>
    /// 导出行数与安全边界（默认值见 <see cref="TaktExcelExportOptions"/>）
    /// </summary>
    public TaktExcelExportOptions Export { get; set; } = new();

    /// <summary>
    /// 校验导入导出上限（防 0、防运维误配超大值导致 OOM）
    /// </summary>
    public void Validate()
    {
        Import.Validate(SectionName);
        Export.Validate(SectionName);
    }
}

/// <summary>
/// Excel 导入配置（appsettings <c>Excel:Import</c> 覆盖默认值）
/// </summary>
public class TaktExcelImportOptions
{
    /// <summary>
    /// 代码硬上限：单文件最大导入行数（含多 Sheet 合计）
    /// </summary>
    public const int HardMaxRowsPerFile = 50_000;

    /// <summary>
    /// 代码硬上限：单文件最大 Sheet 数
    /// </summary>
    public const int HardMaxSheetsPerFile = 50;

    /// <summary>
    /// 代码硬上限：单 Sheet 最大导入行数
    /// </summary>
    public const int HardMaxRowsPerSheet = 50_000;

    /// <summary>
    /// 单文件最大导入行数（含多 Sheet 合计）
    /// </summary>
    public int MaxRowsPerFile { get; set; } = 1000;

    /// <summary>
    /// 单文件最大 Sheet 数量（多 Sheet 导入）
    /// </summary>
    public int MaxSheetsPerFile { get; set; } = 10;

    /// <summary>
    /// 单个 Sheet 最大导入行数（多 Sheet 导入时按 Sheet 校验）
    /// </summary>
    public int MaxRowsPerSheet { get; set; } = 1000;

    /// <summary>
    /// 验证导入配置
    /// </summary>
    /// <param name="sectionName">配置节名称</param>
    public void Validate(string sectionName)
    {
        if (MaxRowsPerFile <= 0 || MaxRowsPerFile > HardMaxRowsPerFile)
        {
            throw new InvalidOperationException(
                $"{sectionName}:Import:MaxRowsPerFile 须在 1～{HardMaxRowsPerFile} 之间（当前 {MaxRowsPerFile}）");
        }
        if (MaxSheetsPerFile <= 0 || MaxSheetsPerFile > HardMaxSheetsPerFile)
        {
            throw new InvalidOperationException(
                $"{sectionName}:Import:MaxSheetsPerFile 须在 1～{HardMaxSheetsPerFile} 之间（当前 {MaxSheetsPerFile}）");
        }
        if (MaxRowsPerSheet <= 0 || MaxRowsPerSheet > HardMaxRowsPerSheet)
        {
            throw new InvalidOperationException(
                $"{sectionName}:Import:MaxRowsPerSheet 须在 1～{HardMaxRowsPerSheet} 之间（当前 {MaxRowsPerSheet}）");
        }
    }
}

/// <summary>
/// Excel 导出配置（appsettings <c>Excel:Export</c> 覆盖默认值）
/// </summary>
public class TaktExcelExportOptions
{
    /// <summary>
    /// 代码硬上限：单次 DB 加载最大行数
    /// </summary>
    public const int HardMaxRowsPerRequest = 50_000;

    /// <summary>
    /// 代码硬上限：单 Sheet 最大行数
    /// </summary>
    public const int HardMaxRowsPerSheet = 100_000;

    /// <summary>
    /// 代码硬上限：单文件最大 Sheet 数
    /// </summary>
    public const int HardMaxSheetsPerFile = 50;

    /// <summary>
    /// 单次导出从数据库加载的最大行数（仓储 <c>GetListForExportAsync</c> Take 上限）
    /// </summary>
    public int MaxRowsPerRequest { get; set; } = 5000;

    /// <summary>
    /// 单个 Excel 工作表最大行数；超出后分批打包为 zip
    /// </summary>
    public int MaxRowsPerSheet { get; set; } = 10000;

    /// <summary>
    /// 单文件最大 Sheet 数量（多 Sheet 导出）
    /// </summary>
    public int MaxSheetsPerFile { get; set; } = 10;

    /// <summary>
    /// 验证导出配置
    /// </summary>
    /// <param name="sectionName">配置节名称</param>
    public void Validate(string sectionName)
    {
        if (MaxRowsPerRequest <= 0 || MaxRowsPerRequest > HardMaxRowsPerRequest)
        {
            throw new InvalidOperationException(
                $"{sectionName}:Export:MaxRowsPerRequest 须在 1～{HardMaxRowsPerRequest} 之间（当前 {MaxRowsPerRequest}）");
        }
        if (MaxRowsPerSheet <= 0 || MaxRowsPerSheet > HardMaxRowsPerSheet)
        {
            throw new InvalidOperationException(
                $"{sectionName}:Export:MaxRowsPerSheet 须在 1～{HardMaxRowsPerSheet} 之间（当前 {MaxRowsPerSheet}）");
        }
        if (MaxSheetsPerFile <= 0 || MaxSheetsPerFile > HardMaxSheetsPerFile)
        {
            throw new InvalidOperationException(
                $"{sectionName}:Export:MaxSheetsPerFile 须在 1～{HardMaxSheetsPerFile} 之间（当前 {MaxSheetsPerFile}）");
        }
    }
}
